blank_issues_enabled: true
contact_links:
  - name: Hypercoin Core Security Policy
    url: https://github.com/hypercoin/hypercoin/blob/master/SECURITY.md
    about: View security policy
  - name: Hypercoin Core Developers
    url: https://hypercoincore.org
    about: Hypercoin Core homepage
